"""
Main FastAPI application entry point for Verified ID Employee Verification.
"""

import logging
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.docs import get_swagger_ui_html
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request

from .api.v1.router import api_router
from .core.config import app_settings

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=app_settings.LOG_LEVEL,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

# Resolve once at module load — avoids repeated filesystem calls per request.
project_root = Path(__file__).resolve().parents[2]
frontend_dist = (project_root / "frontend").resolve()
frontend_index = frontend_dist / "index.html"


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Add security headers to every HTTP response."""

    # Build CSP once at class level — one directive per list entry, auditable.
    _CSP_DIRECTIVES: list[str] = [
        "default-src 'self'",
        "script-src 'self' 'unsafe-inline'",  # Angular requires unsafe-inline
        "style-src 'self' 'unsafe-inline'",  # Bootstrap inline styles
        "img-src 'self' data: https:",  # logos, QR codes base64
        "font-src 'self' data:",  # Bootstrap Icons embedded font
        "connect-src 'self'"  # API calls + Azure endpoints
        " https://login.microsoftonline.com"  # MSAL auth
        " https://verifiedid.did.msidentity.com",  # Verified ID service
        "worker-src 'self'",  # Angular Service Worker (PWA)
        "frame-ancestors 'none'",  # replaces X-Frame-Options
    ]
    _CSP: str = "; ".join(_CSP_DIRECTIVES) + ";"

    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["X-XSS-Protection"] = "1; mode=block"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Permissions-Policy"] = (
            "camera=(), microphone=(), geolocation=(), payment=()"
        )
        response.headers["Strict-Transport-Security"] = (
            "max-age=31536000; includeSubDomains"
        )
        response.headers["Content-Security-Policy"] = self._CSP
        return response

def _resolve_safe_path(full_path: str) -> Path | None:
    """
    Resolve a URL path to a filesystem path safely.

    Returns the resolved Path if it is a file strictly inside frontend_dist,
    or None if the path is unsafe, empty, or points outside the allowed root.

    This prevents path traversal attacks (e.g. '../../etc/passwd',
    '%2e%2e%2fetc', null-byte injection) by using Path.is_relative_to()
    which operates on the fully resolved absolute path.

    Args:
        full_path: Raw URL path segment from the request.

    Returns:
        Path | None: Safe resolved path, or None if rejected.
    """
    # Reject empty paths and dot-only segments immediately.
    stripped = full_path.strip()
    if not stripped or stripped in (".", ".."):
        return None

    # Resolve to absolute path — collapses all '..' and symlinks.
    candidate = (frontend_dist / stripped).resolve()

    # The candidate must be strictly inside frontend_dist (not equal to it).
    # is_relative_to() returns True even when candidate == frontend_dist,
    # so we add an explicit equality check to block directory root access.
    if candidate == frontend_dist:
        return None

    if not candidate.is_relative_to(frontend_dist):
        logger.warning(
            "Path traversal attempt blocked: raw=%r resolved=%s",
            full_path,
            candidate,
        )
        return None

    # Only serve regular files, never directories or special files.
    if not candidate.is_file():
        return None

    return candidate

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan events."""
    logger.info("Starting Verified ID application...")
    yield
    logger.info("Shutting down Verified ID application...")

app = FastAPI(
    title="Employee Verified ID API",
    description="API for verifying employee identity using Microsoft Entra Verified ID",
    version="1.0.0",
    lifespan=lifespan,
    docs_url=None,
    openapi_url="/api/openapi.json" if app_settings.SWAGGER_ENABLE else None,
)

# Order matters: SecurityHeadersMiddleware is registered first so it wraps
# the CORS middleware and injects headers on ALL responses, including
# preflight OPTIONS responses generated by CORSMiddleware.
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=app_settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router, prefix="/api/v1")

@app.get("/api/docs", include_in_schema=False)
async def swagger_ui():
    return get_swagger_ui_html(
        openapi_url="/api/openapi.json",
        title="Employee Verified ID API",
        swagger_favicon_url="/favicon.ico",
    )

@app.get("/api/health")
async def health_check() -> dict:
    """Health check endpoint."""
    return {"status": "healthy", "service": "VerifID API"}

@app.get("/{full_path:path}", include_in_schema=False)
async def serve_spa(full_path: str) -> FileResponse:
    """
    Serve Angular static files with path traversal protection.

    Requests for existing static assets (JS, CSS, images) are served directly.
    All other paths fall back to index.html to support client-side SPA routing.
    Unknown or unsafe paths also fall back to index.html rather than 404-ing,
    letting the Angular router handle the error page.
    """
    if not frontend_index.is_file():
        logger.error("SPA index.html not found at %s", frontend_index)
        raise HTTPException(status_code=503, detail="Frontend not available.")

    safe = _resolve_safe_path(full_path)
    if safe is not None:
        return FileResponse(safe)

    # SPA fallback: Angular router handles unknown client-side routes.
    return FileResponse(frontend_index)
